version: '3.10'
services:
  bot_faturamento_fornecedor:
    image: cx_python
    container_name: some_time_bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/volume
    restart: on-failure
    tty: true
    environment:
      TZ: "America/Fortaleza"
    command: "python3 main.py"